apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-prod
resources:
  - ../../base/podinfo
patches:
  - path: patch-configmap.yaml
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
