apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tools-rs
  namespace: platform-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools-rs
  template:
    metadata:
      labels:
        app: tools-rs
    spec:
      containers:
        - name: tools
          image: busybox:1.36
          command: ["sh", "-c", "while true; do date; sleep 30; done"]
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
